# -*- coding: utf-8 -*-
import sys
import time

# Form implementation generated from reading ui file 'desktop.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget
import requests
import wallpaper



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(363, 238)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(110, 60, 121, 111))
        self.pushButton.setObjectName("pushButton")
        #信号(事件)与槽(函数)
        #发生什么事件 触发什么函数
        #触发什么信号 槽函数就会相应产生反应
        #当前xx控件发生click的信号链接一个槽函数
        self.pushButton.clicked.connect(self.btn_click)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "随机壁纸工具"))
        self.pushButton.setText(_translate("Form", "获取图片"))
    def btn_click(self):
        #需求向我们远程发起一个网络请求
        #安装我们第三方的模块 pip install requests
        response=requests.get("https://api.vvhan.com/api/view?type=json")
        json=response.json()
        #从我们所有返回的数据中获取到壁纸的网络地址
        imgurl=json['imgurl']
        #下载这个壁纸到本地的电脑 我们现在设置一下，壁纸下载的位置在F盘的download文件夹下
        #发起二次请求  下载图片 将图片保存到本地F://download
        response_img=requests.get(imgurl)
        img_byte=response_img.content
        f = open("f://download//1.jpg", "wb")
        f.write(img_byte)
        f.close()
        #将我们桌面设置为我们下载的壁纸
        #延迟操作 休眠
        time.sleep(3);
        wallpaper.set_img_as_wallpaper("f:\\download\\1.jpg")




if __name__ == '__main__':
    #创建一个程序
    app=QApplication(sys.argv)
    #创建一个视图
    window=QWidget()
    #创建我们的界面
    ui=Ui_Form()
    #初始化界面
    ui.setupUi(window)
    #显示视图
    window.show()
    #让程序保持运行状态
    sys.exit(app.exec_())